version: "23.0.5"
services:
  discovery:
    build: ./eureka
    ports:
      - 8761:8761
    image: eureka

  book:
    build: ./Book
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8082:8082
    image: bookms
    depends_on:
      - discovery
  borrowing:
    build: ./Borrowing
    environment:
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - 8081:8081
    image: borrowingms
    depends_on:
      - discovery